# Model Training

# 1. Import Data and Required Pakcages

### Importing Pandas, Numpy, Matplotlib, Seaborn and Warning Library.

In [14]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Modeling
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression, RidgeClassifier, Lasso
from sklearn.model_selection import RandomizedSearchCV, train_test_split
# from catboost import CatBoostClassifier
# from xgboost import XGBClassifier
import warnings

# Improt the CSV Data as Pandas DataFrame

In [3]:
df = pd.read_csv('data/iris.csv')

# Show Top 5 Records

In [4]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

# Preparing X and Y variables

In [5]:
X = df.drop(columns=["target", "species"], axis=1)

In [7]:
y = df["target"]

In [10]:
# Create column transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
# cat_features = X.select_dtypes(include="object").columns


from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
# oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        # ("OneHotEncoder", oh_transformer, cat_features),
        ("StandardScaler", numeric_transformer, num_features,)
    ]
)

In [12]:
X = preprocessor.fit_transform(X)

In [19]:
# seperate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train.shape, X_test.shape

((120, 4), (30, 4))

## Create an Evaluta Function to give all metrics after model training

In [20]:
def evaluate_model(true, predicted):
    # f1 = f1_score(true, predicted)
    acc = accuracy_score(true, predicted)
    return acc

In [21]:
models = {
    "Linear Regression": LogisticRegression(),
    "Lasso": Lasso(),
    "RidgeClassifier": RidgeClassifier(),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

In [25]:
model_list = []
acc_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluation Train and Test dataset
    model_train_acc = evaluate_model(y_train, y_train_pred)
    model_test_acc = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Performance for Training set')
    print("- Accuracy : {:.4f}".format(model_train_acc))

    print('------------------------------------------')

    print('Model Performance for Test set')
    print("- Accuracy : {:.4f}".format(model_test_acc))
    acc_list.append(model_test_acc)

    print('='*35)
    print('\n')

Linear Regression
Model Performance for Training set
- Accuracy : 0.9583
------------------------------------------
Model Performance for Test set
- Accuracy : 0.9333
===================================


Lasso
Model Performance for Training set
- Accuracy : 0.3333
------------------------------------------
Model Performance for Test set
- Accuracy : 0.3333
===================================


RidgeClassifier
Model Performance for Training set
- Accuracy : 0.8750
------------------------------------------
Model Performance for Test set
- Accuracy : 0.7667
===================================


KNN
Model Performance for Training set
- Accuracy : 0.9750
------------------------------------------
Model Performance for Test set
- Accuracy : 0.9333
===================================


Decision Tree
Model Performance for Training set
- Accuracy : 1.0000
------------------------------------------
Model Performance for Test set
- Accuracy : 0.9667
===================================


Random Forest
Model Performance for Training set
- Accuracy : 1.0000
------------------------------------------
Model Performance for Test set
- Accuracy : 0.9667
===================================

## Results

In [26]:
pd.DataFrame(list(zip(model_list, acc_list)), columns=['Model Name', 'Accuracy_Score']).sort_values(by=['Accuracy_Score'], ascending=False)

          Model Name  Accuracy_Score
4      Decision Tree        0.966667
5      Random Forest        0.966667
0  Linear Regression        0.933333
3                KNN        0.933333
2    RidgeClassifier        0.766667
1              Lasso        0.333333

## Decision Tree

In [27]:
tree_model = DecisionTreeClassifier()
tree_model.fit(X_train, y_train)
y_pred = model.predict(X_test)
score = accuracy_score(y_test, y_pred)*100
print("Accuracy of the model is %.2f" %score)

Accuracy of the model is 96.67

## Plot y_pred and y_test

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30